version: '3'

services:

  nginx:
    image: nginx:stable-alpine
    container_name: laravel_blog_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./:/var/www/html
      # - /var/www/html/vendor
      - ./default.conf:/etc/nginx/conf.d/default.conf
      # - ./home/webwerks/secure_storage:/secure_storage
    depends_on:
      - php

  # mysql:
  #   image: mysql:5.7.30
  #   container_name: laravel9_mysql
  #   restart: unless-stopped
  #   tty: true
  #   ports:
  #     - "4406:3306"
  #   volumes:
  #     - ./docker/mysql:/var/lib/mysql
  #   environment:
  #     MYSQL_DATABASE: homestead
  #     MYSQL_USER: homestead
  #     MYSQL_PASSWORD: secret
  #     MYSQL_ROOT_PASSWORD: secret
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   networks:
  #     - laravel9

  php:
    image: public.ecr.aws/b5x7u7t9/infokes-ecr-pub:simpleblog
    container_name: simpleblog
    # volumes:
    #   - ./:/var/www/html
    #   - /var/www/html/vendor

      # - ./docker/php/config:/usr/local/etc/php
    command: php artisan serve --host=0.0.0.0 --port=9000  
    ports:
      - "9000:9000"
  

  # laravel_blog_mysql:
  #   image: mysql:latest
  #   command: --default-authentication-plugin=mysql_native_password
  #   environment:
  #     MYSQL_ROOT_PASSWORD: rootpassword
  #     MYSQL_USER: homestead
  #     MYSQL_PASSWORD: homestead
  #     SERVICE_TAGS: dev
  #     SERVICE_NAME: mysql
  #   # ports:
  #   #   - 3306:3306
  #   volumes:
  #     - laravel_blog_db_data:/var/lib/mysql
  adminer_laravel_blog:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: laravel_blog_mysql
    ports:
      - 8080:8080
volumes:
  laravel_blog_db_data:


      