version: '3'
services:
  nginx:
    image: nginx:stable-alpine
    container_name: laravel_blog_nginx
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www/html
      - /var/www/html/vendor
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf      
    depends_on:
      - php

  php:
    image: public.ecr.aws/b5x7u7t9/infokes-ecr-pub:simpleblog
    container_name: simpleblog
    ports:
      - "9004:9000"  
volumes:
  laravel_blog_db_data:


      
